"""Add resume_type column to resume_manager

Revision ID: 5e2145ed9af5
Revises: 20f7a81e528e
Create Date: 2025-01-24 09:46:49.006971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e2145ed9af5'
down_revision: Union[str, None] = '20f7a81e528e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
